### PR TITLE
Project report and missing report types

### PR DESCRIPTION
**Pull request by jerryreid**
B-02103, B-01996

### CODE REVIEW

**Comment by shawn905** [comment]
@jerryreid The only thing that I may change is the name of the report. I think Projects with milestones with tasks could be called 'Projects with Milestones and Tasks'. What's your view on this?

**Comment by jerryreid** [comment]
Works for me. Do I make this change or do you?

--
Best Regards,

Jerry Reid
Passage Technology
www.passagetech.com
jerry.reid@passagetech.com
Direct: 1-224-552-0080
Twitter:  @passagetech

**Comment by shawn905** [comment]
@jerryreid when working on the rollup helper team when someone provided feedback the developer initially working on the pull request would make the changes. But I will make the change and merge into master since I know you are busy.

**Comment by jerryreid** [comment]
Need to query report id by name. Need to update metadata on report folder.

**Pull request merged**
